---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.3.37

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  # Ubuntu 18.04 currently fails: https://github.com/chef-cookbooks/chef-server/issues/155
  # with the error: "No artifacts found matching criteria."
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[cwb-chef-server::default]
    attributes:
