# Initially based on (switched to full Docker config by 2020-04-21) https://github.com/chef-cookbooks/enterprise-chef-common/blob/master/.travis.yml
# Updated based on: https://gitlab.openminds.be/mirror/ark/blob/master/.travis.yml
# kitchen-in-travis-native: https://github.com/zuazo/kitchen-in-travis-native
# Use Travis's container-based infrastructure
os: linux
dist: xenial
language: ruby
services: docker

addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

env:
  jobs:
  - INSTANCE=ubuntu-1804
  # Add on demand:
  - INSTANCE=ubuntu-1604

before_install:
  - cd cookbooks/cwb-server

install:
  - echo "skip bundle install, using ChefDK instead"

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  # Ensure we make ChefDK's Ruby the default
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  # Accepting Chef licence is required from version >15
  - CHEF_LICENSE=accept chef exec gem list

script:
  # Run all test stages: lint, syntax, unit_test, integration_test
  - make all_tests INSTANCE=${INSTANCE}
