---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
    # To run test-kitchen for OS X, create a box for 10.10, and add it to vagrant
  - name: macosx-10.10
    driver_config:
      box: chef/macosx-10.10
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2

suites:
<% %w(11 12).each do |version| %>
  - name: default_chef<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[test]
<% end %>
