AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
    - Policyfile.rb
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
LineLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
