---
# Example: https://github.com/sous-chefs/postgresql/blob/master/.kitchen.dokken.yml
driver:
  name: dokken
  privileged: true
  # Fixing systemd: https://github.com/someara/kitchen-dokken#process-orientation
  pid_one_command: /bin/systemd
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  intermediate_instructions:
    # For setting timezone via `/usr/bin/timedatectl`: dbus tzdata
    # For PostgreSQL en_US.utf8 locals: locales
    # For sudo in deploy#export systemd templates: sudo
    # For integration tests using wget
    - RUN apt-get update && apt-get install -y apt-transport-https net-tools dbus tzdata locales sudo wget
    # Ensure that the default locale exists
    - RUN locale-gen en_US.utf8

platforms:
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04

transport:
  name: dokken

provisioner:
  name: dokken
  log_level: debug

verifier:
  # Required for `serverspec` https://github.com/someara/kitchen-dokken/issues/78#issuecomment-298314150
  root_path: '/opt/verifier'
  sudo: false
