---
driver:
  name: dokken
  privileged: true
  # Fixing systemd: https://github.com/someara/kitchen-dokken#process-orientation
  pid_one_command: /lib/systemd/systemd
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  intermediate_instructions:
    - RUN /usr/bin/apt-get update
    # For setting timezone via `/usr/bin/timedatectl`: dbus,tzdata
    - RUN /usr/bin/apt-get install -y apt-transport-https net-tools dbus tzdata

transport:
  name: dokken

provisioner:
  name: dokken
  log_level: debug

verifier:
  # Required for `serverspec` https://github.com/someara/kitchen-dokken/issues/78#issuecomment-298314150
  root_path: '/opt/verifier'
  sudo: false
