---
driver:
  name: dokken
  privileged: true
  # Fixing systemd: https://github.com/someara/kitchen-dokken#process-orientation
  pid_one_command: /lib/systemd/systemd
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  intermediate_instructions:
    # For setting timezone via `/usr/bin/timedatectl`: dbus tzdata
    # For PostgreSQL en_US.UTF-8 locals: locales
    # For sudo in deploy#export systemd templates: sudo
    # For integration tests using wget
    - RUN apt-get update && apt-get install -y apt-transport-https net-tools dbus tzdata locales sudo wget
    # Setup en_US.UTF-8 local for PostgreSQL server installation => builds `/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/pgscripts-9.6.mo`
    - RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && echo 'LANG="en_US.UTF-8"'>/etc/default/locale && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8

transport:
  name: dokken

provisioner:
  name: dokken
  log_level: debug

verifier:
  # Required for `serverspec` https://github.com/someara/kitchen-dokken/issues/78#issuecomment-298314150
  root_path: '/opt/verifier'
  sudo: false
