---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.3.37
  log_level: info

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
# Node attributes: cat /tmp/kitchen/nodes/default-ubuntu-1604.json
  - name: ubuntu-16.04
  - name: ubuntu-18.04

provisioner:
  name: chef_zero
  version: 14.3.37

suites:
  - name: default
    run_list:
      - recipe[cwb-server::default]
    attributes:
      # For a list of time zones see: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      tz: Europe/Zurich
      cwb-server:
        app:
          branch: master
        db:
          password: cloud
          postgres_password: rootcloud
        ssh:
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAIEA0p7NpZ+pZMwaKQVdTLsQjOvqG2tzl5lu4oUNgY6PG75DFyMG25Pu
C/PcVu1+5lOEj5hZJNFnUbdT8UCLIWoRlGBMnW0X11KIHD+qIashdGa8c+f7kX7phf0/Ti
yuLED7Rm4fTST5Yx7XHHZIF4gqK+yv2SyJR29i0uBVNsajUjUAAAIIL/3aoS/92qEAAAAH
c3NoLXJzYQAAAIEA0p7NpZ+pZMwaKQVdTLsQjOvqG2tzl5lu4oUNgY6PG75DFyMG25PuC/
PcVu1+5lOEj5hZJNFnUbdT8UCLIWoRlGBMnW0X11KIHD+qIashdGa8c+f7kX7phf0/Tiyu
LED7Rm4fTST5Yx7XHHZIF4gqK+yv2SyJR29i0uBVNsajUjUAAAADAQABAAAAgDt3qwjAc8
uJ9Tjv0s//YUTot0jWpeR/5db/SjjyT2W96qN1uFH3CpdFW0kP9WyC2ELS+Rh0J3/jC0hq
uN3OXPfMll5xwGwKdvMH6IRyesQqiG4myFSfvXx1eKh3CiZR3SGukJvGZgAcHcm2zHuoMW
xFvRd65UUhDPLDVTNreCRhAAAAQQCn2qOZt1hduuBDto1f6vPiXBMzRsdBiVS7/B/iQacb
vYhR1HvIRi7u9MgfpLuNT0WvoKw+46/jZCR/eEFGw+G1AAAAQQDy9rZ+ra82KNOmgpRzhz
c1arzAV3nh9zxlF3+jL7Zp9NstE9ABW8173hohKKR1jzPyoJvtDypE3JMvWQYbxVXbAAAA
QQDd69RyP6/DWFhw7dPmQ7T8BOUY8RPZWQzKcYwiTiFWJbEm5JuzQIY5FQp1k6DUOREcyz
XVKOAYO9Hk5NqpKF0vAAAADGN3YkB0ZXN0LmNvbQECAwQFBg==
-----END OPENSSH PRIVATE KEY-----
          key_name: cwb@test.com
        providers:
          aws:
            access_key: my_aws_access_key
          google:
            project_id: my_google_project_id
            json_key_FILE: {"google": "my_google_secret"}
          azure:
            tenant_id: my_azure_tenant_id
