# -*- mode: ruby -*-
# vi: set ft=ruby :

source 'https://rubygems.org'

gem 'rake'

group :integration do
  gem 'test-kitchen', '~> 1.16'
end

# group :vagrant do
#   gem 'vagrant-wrapper', '~> 2.0', '>= 2.0.3'
#   gem 'kitchen-vagrant', '~> 1.1'
# end

group :docker do
  gem 'kitchen-docker', '~> 2.6'
end
